//Character
import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


const defaultEndpoint = 'https://rickandmortyapi.com/api/character'

// grap the query from the url 
export async function getServerSideProps({ query }) {
  const { id } = query
  const res = await fetch(`${defaultEndpoint}/${id}`)
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}

export default function Character({ data }) {
  console.log('data', data);
  const { name, image, gender, location, origin, species, status } = data;
  return (
    <div>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href='/'>Home</Link>

      <main className="container">
        <h1>
          {name}
        </h1>

        <div classname="container">
          <div className="row g-0">
            <div className="col-md-4">
              <img src={image} alt={name} />
            </div>
            <div className="col-md-8">
              <div className="card-body">
                <h5 className="card-title">{name}</h5>
                <p className="card-text">
                  Character details
                </p>
                <ul>
                  <li>
                    <strong>Name:</strong> {name}
                  </li>
                  <li>
                    <strong>Status:</strong> {status}
                  </li>
                  <li>
                    <strong>Gender:</strong> {gender}
                  </li>
                  <li>
                    <strong>Species:</strong> {species}
                  </li>
                  <li>
                    <strong>Location:</strong> {location?.name}
                  </li>
                  <li>
                    <strong>Originally From:</strong> {origin?.name}
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>


      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
