import Head from 'next/head'
import Hero1 from '../Components/Hero/Hero1/Hero1';
import MainLayout from '../Components/Layouts/MainLayout';


export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero1 />
      This is the index page.
    </MainLayout>
  )
}
